### ISSUE TITLE
Add qulice checks

### ISSUE THREAD

**Issue by volodya-lombrozo** [volodya-lombrozo/test-naming-conventions#15]
We have to add [qulice](https://www.qulice.com) checks to the project for future maintainability

**Comment by l3r8yJ** [comment]
can i take this one?

**Comment by volodya-lombrozo** [comment]
@l3r8yJ Sure, go ahead, but I'm afraid it will be painful :) 
If it will require lots of changes just ignore some classes or tests.

**Comment by l3r8yJ** [comment]
@volodya-lombrozo i understand, but it's better to do it sooner

**Comment by l3r8yJ** [comment]
@volodya-lombrozo does it make sense to duplicate the plugin usage examples from `README` into the `test/resources` directory?
`qulice` requires `package-info.java` in every package, but there are problems with the resource folder because it's not a package

**Comment by volodya-lombrozo** [comment]
@l3r8yJ No it doesn't. Are you sure about resource directory? Can you post the exception? Apparently you have to add `package-info.java` into 2 places:
- src/main/java/com/github/lombrozo/testnames
- src/test/java/com/github/lombrozo/testnames

**Comment by volodya-lombrozo** [comment]
@l3r8yJ I see. It's because we have some java classes in resources. I believe we have to just ignore checks inside `src/test/resources`. We do the same in `eo`:
```xml
 <plugin>
            <groupId>com.qulice</groupId>
            <artifactId>qulice-maven-plugin</artifactId>
            <configuration>
              <excludes>
                <exclude>checkstyle:/src/it.*</exclude>
                <exclude>checkstyle:/src/test/resources/.*</exclude>
                <exclude>pmd:/src/it.*</exclude>
                <exclude>pmd:/src/test/resources/.*</exclude>
                <exclude>duplicatefinder:.*</exclude>
                <exclude>xml:/src/test/resources/META-INF/maven/plugin.xml</exclude>
              </excludes>
            </configuration>
          </plugin>
```

**Comment by l3r8yJ** [comment]
@volodya-lombrozo also in some methods i see picture like this:
```java
for(Object obj : objects) {
	// here some new collection
	otherCollection.forEach(obj -> {
		//some code
	});
}
```
maybe we should use one type of iteration to make the code more uniform?

**Comment by volodya-lombrozo** [comment]
@l3r8yJ Yes, why not. But it's better to create a separate issue for that.
