### ISSUE TITLE
Add test-naming-conventions-check

### ISSUE THREAD

**Issue by l3r8yJ** [volodya-lombrozo/test-naming-conventions#17]
I'm think it would be nice to have this in project, @volodya-lombrozo what do you think?

**Comment by volodya-lombrozo** [comment]
@l3r8yJ What "this"? Do you mean the plugin itself?

**Comment by l3r8yJ** [comment]
@volodya-lombrozo add `test-naming-conventions` check into `test-naming-conventions` build
